### ISSUE TITLE
Explicit getter methods are unnecessary.

### ISSUE THREAD

**Issue by harlanhaskins** [bmbowdish/Swiftfall#21]
In Swift, you only need to mark a property as `public` in order to expose its getter. Swift automatically synthesizes getter/setter methods for properties, unlike languages like Java.

The explicit getters such as this:

```swift
let name: String?
public func getName() -> String? {
  return self.name
}
```

...can be replaced with:

```swift
public let name: String?
```

...and used by just referencing `card.name`.

**Comment by harlanhaskins** [comment]
Wait I missed #20, which addresses this. Great work!

**Comment by bmbowdish** [comment]
I actually wanted this as an Issue so it was written down somewhere, thanks! :)
