### ISSUE TITLE
Use convertToSnakeCase when Swift 4.1 is released

### ISSUE THREAD

**Issue by harlanhaskins** [bmbowdish/Swiftfall#22]
Swift 4.1 introduces a new property on `JSONDecoder` called `keyEncodingStrategy`. This will allow the JSON encoder/decoder to convert property names spelled in camel case like `let manaCost: Int?` into `mana_cost` when reading from or writing to JSON. This way you get nice Swifty property names that don't use `snake_case`, and the decoder automatically reads the snake case versions from the JSON.

https://www.hackingwithswift.com/articles/52/swift-4-1-improves-codable-with-keydecodingstrategy

**Comment by bmbowdish** [comment]
That is sooooo cool.

**Comment by bmbowdish** [comment]
Done in #50
