### ISSUE TITLE
Card Pricing

### ISSUE THREAD

**Issue by JesseRubio** [bmbowdish/Swiftfall#47]
Scryfall has recently changed the way prices are fetched.
It is no longer:
      public let usd: String?

It is now prices[usd]
How could we write that in swift? I tried many things but with no solution.

**Comment by bmbowdish** [comment]
I’ll look into it after work! Thanks for leaving the issue.

**Comment by bmbowdish** [comment]
https://github.com/bmbowdish/Swiftfall/pull/49

Fixed
